remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Reproducing "Dynamic Adaptation of Software-defined Networks for IoT Systems: A Search-based Approach"]
description: ['Members: Agresh Bharadwaj, Ayush Garg, Tulika Sureka, Vishnu Teja Narapareddy, and Vivek Gupta']
github:
  is_project_page: false
  
  
  
